services:
    # PHP service
    restapi:
        build: ./restapi/
        container_name: simple_rest_api
        working_dir: /var/www/
        volumes:
            - ./restapi:/var/www
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - simple-rest-api-network

    # MySQL database service
    restapidb:
        image: mysql:latest
        container_name: simple_rest_api_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./restapi:/var/www
        env_file:
            - .env
        networks:
            - simple-rest-api-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: simple_rest_api_nginx
        ports:
            - 80:80
        volumes:
            - ./restapi:/var/www
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - simple-rest-api-network
            
networks:
    simple-rest-api-network:
        driver: bridge
