version: "3.8"
services:
    # PHP service
    app:
        build: ./app/
        container_name: simple_nginx_php_mysql_app
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
            - ./app/conf/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - simple-app-network

    # MySQL database service
    db:
        image: mysql:latest
        container_name: simple_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - .env
        networks:
            - simple-app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: simple_nginx
        ports:
            - 80:80
        volumes:
            - ./app:/var/www
            - ./app/conf/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - simple-app-network
            
networks:
    simple-app-network:
        driver: bridge
